### PR TITLE
Work in progress...

### PR DESCRIPTION
**Pull request by ryno83**
For issue/feature request #25
Not finish yet. Still working on it...

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Nice! Thanks a lot!

may I ask you to implement this on basis of the Appframework as documented here https://doc.owncloud.org/server/8.0/developer_manual/app/index.html

This will allow us to properly unit test the code - many thanks!

**Comment by karlitschek** [comment]
Very nice. We have to make sure that it works in all scenarios. So if a user is not allowed to change password, email, display name, ... then it shouldn't show up in the wizard. Basically the same logic then on the personal page.
@MTRichards 
@jancborchardt

**Comment by jancborchardt** [comment]
@ryno83 great stuff! cc @owncloud/designers

**Comment by jancborchardt** [comment]
@ryno83 what happened? :) Let us know if you need any help.

**Comment by ryno83** [comment]
@jancborchardt Because I was new to git and github, I started modifiing the master branch of my fork. I noticed it last week and it was confusing for me (I want to keep my master branch egal to owncloud/firstrunwizard). The solution I found is to close this pull request.

Now, you can follow/comment/help with the pull request #27 !

**Pull request closed without merging**
