### PR TITLE
Add a controller and remove /ajax

### PR DESCRIPTION
**Pull request by ryno83**
@DeepDiver1975 @jancborchardt Hi guys, a new PR with pagecontroller and no more /ajax/ files + remove use of deprecated method in template. Is it better like this ?

### CODE REVIEW

**Comment by jancborchardt** [comment]
A lot of code seems to have been changed and removed, including tests. Need code review here @DeepDiver1975 @PVince81 @karlitschek

**Comment by jancborchardt** [comment]
@ryno83 sorry for missing this PR so far by the way!

**Comment by ryno83** [comment]
@DeepDiver1975 @PVince81 @karlitschek @jancborchardt 
This is what I have done in this PR : 

1 : I removed the ajax/enable.php and ajax/disable.php files. The "enable" feature wasn't use at all and the "disable" was use when closing the modal box. Instead, I'm disabling the app for the user immediatly after activate.js was loaded by app.php. This prevent the 
modal box from loading again and again.

2 : I created controller/pagecontroller.php with is route to replace the wizard.php. I adjust the firstrunwizard.js to work with the controller.

3 : I removed lib/config.php and is test file (tests/lib/configtest.php) because it's not needed anymore

**Comment by jancborchardt** [comment]
@ryno83 can you rebase with current master?

Also @PVince81 @MorrisJobke @karlitschek @DeepDiver1975 can you please have a look at this? Needs code review.

**Comment by jancborchardt** [comment]
cc also @LukasReschke

**Comment by ryno83** [comment]
@jancborchardt Rebase done !

**Comment by jancborchardt** [comment]
@ryno83 seems like improvements are not welcome here anymore, let’s continue at https://github.com/nextcloud/firstrunwizard :)

**Comment by DeepDiver1975** [comment]
Just to make a point: improvements are always welcome - in any area of ownCloud!
But it is up to the submitter of the change to make sure things are getting reviewed and merged.

At the end it will help nobody (neither submitter, nor the project) if issues and pull requests are rotting around.

@ryno83 if you are still interested in contributing please let us know and we will reopen the pr right away. THX

**Comment by jancborchardt** [comment]
For issues automatic messages are fine, but for pull requests they are inadequate. At least a real contributor should make a comment, otherwise it seems very off-putting. Just some feedback on how it looks from a community-side.

**Comment by DeepDiver1975** [comment]
@jancborchardt as we invented this script back in Stuttgart 2015 we had two intentions:

- close outdated and no longer valid issues
- get attention back on long open and rotting issues

The whole discussion in here shows that the last point works quite good for pull requests as well - right? :wink: 

I'm happy to discuss the comment which is added automatically to focus more on the intention of the automatic process.

**Pull request closed without merging**
