### PR TITLE
Add occ command to reset for all users

### PR DESCRIPTION
**Pull request by tomneedham**
For admins to show new features / clients / manuals to their users, then can theme the firstrunwizard again and trigger it nicely

 - [x] Test on Config class method

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
occ already has a command to set user preferences .... maybe we add an option --all-users over there?

**Comment by PVince81** [comment]
I wonder if we need a base class in core for all commands that apply to all users... The number of commands with "one user", "multiple users" or "multiple group" or "all" as arguments is increasing and we keep on reimplementing.

**Comment by tomneedham** [comment]
Rebased

**Comment by PVince81** [comment]
please take over. goal is just to finish, no need to add further options for now

**Comment by PVince81** [comment]
@sharidas ^

**Comment by sharidas** [comment]
Ouch. I wonder if this is tested. Sorry no offense here. But this app has missing namespace in the info.xml. And as a result the command `occ` fails. I have updated the PR with the same. Below is the result I have verified in the console:
```
 sujith@sujith-ownCloud  ~/test/owncloud3   master ●  ./occ firstrunwizard:reset-all
Cannot load Xdebug - it was already loaded
Resetting firstrunwizard for all users
    1 [============================]
Done
 sujith@sujith-ownCloud  ~/test/owncloud3   master ● 
```

**Comment by sharidas** [comment]
@PVince81 The pull request is ready for review. The CI is cleared.

**Comment by tomneedham** [comment]
> But this app has missing `namespace` in the info.xml. And as a result the command `occ` fails.

Nice spot. My guess is a osx vs linux filesystem casing issue I've seen before with the autoloader. So probably worked for me locally but on a linux box it dies. Good catch!

**Comment by PVince81** [comment]
as firstrunwizard is bundled, we might want to add this addition in the core changelog or release notes only ? @pmaier1

**Comment by pmaier1** [comment]
> core changelog or release notes

both, plx

**Comment by phil-davis** [comment]
Backport `stable10` #93

**Pull request merged**
