### PR TITLE
Update colorbox to v1.6.4, fixes IE11

### PR DESCRIPTION
**Pull request by PVince81**
Fixes first run wizard in IE11.

Note that the issue itself prevents other JS to run so the file list will appear empty for example.
So this is an important fix !

Please review @jvillafanez @PhilippSchaffrath @DeepDiver1975 

To be backported to 9.1. Other versions not affected.

Fixes https://github.com/owncloud/core/issues/26438

### CODE REVIEW

**Comment by PVince81** [comment]
cc @davitol if you want to test if other browsers like Safari still behave properly with this new version

**Comment by davitol** [comment]
@PVince81 Cannot reproduce the issue owncloud/core#26438 using Internet Explorer 11 Version 11.494.10586.0  as browser.
But the First time wizard did not pop up when using this browser the 1st time. This PR solves this problem so IMO :+1:

**Comment by PVince81** [comment]
If the wizard did not pop up either IE ignored the error instead of breaking, or the pop up was already marked as "already shown once". You can usually go to the personal page, there's a button "show wizard again"

**Comment by davitol** [comment]
> You can usually go to the personal page, there's a button "show wizard again"

Yes, I did and it appeared without need of the patch and everything went fine. I meant about the 1st time I logged in the server, that when it did not appear using IE.

**Comment by davitol** [comment]
> cc @davitol if you want to test if other browsers like Safari still behave properly with this new version

Tested with and without the PR and it works like a charm

**Comment by PVince81** [comment]
stable9.1: https://github.com/owncloud/firstrunwizard/issues/57

**Pull request merged**
